### ISSUE TITLE
Feature #1: User can filter games by genre

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/game-repository#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter games by genre

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on a genre of games and the page will be loaded with games of only that genre

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-1-mobile](https://github.com/Malcolm-Abbott/front-end-project/assets/136769102/c238162c-a044-4540-978d-fdf66ca3f8e1)
![feature-1-desktop](https://github.com/Malcolm-Abbott/front-end-project/assets/136769102/7e0fa8c2-9ea3-48a2-b69f-4542fa12af5b)
![feature-1b-mobile](https://github.com/Malcolm-Abbott/front-end-project/assets/136769102/631f57d3-c7b9-4e27-a69e-ea8d50841fd8)
![feature-1b-desktop](https://github.com/Malcolm-Abbott/front-end-project/assets/136769102/4c94fcb7-2041-48ab-aef0-5259795f690f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Header Element outside of the container to match the figma
- [x] Create an HTML skeleton
  - [x] Include a data-view div for view swapping
  - [x] Use the appropriate classes adopting a mobile-first paradigm in your HTML layout design, ensuring responsiveness to both mobile and desktop 
  - [x] Include an unordered list to place the fetch request items inside of as list items
- [x] Style the page with CSS
  - [x] Ensure the page is responsive to both mobile and desktop
- [x] Create dummy entries inside of the unordered list to match the figma
- [x] Define a `renderGames` function that takes one parameter: game.
  - [x] This function should generate and return a DOM tree of the appropriate fetched API objects
- [x] Swap out your dummy list items for your `renderGames` list items once functionality is ensured to be working as expected
- [x] Add a `click` event listener on your unordered list that:
  - [x] Generates a new dom tree of list items representing the games of the chosen genre
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
